name: triggers
run-name: Triggers!

on:
  push:
    branches: ["main", "aprendiendo-**"]
    paths:
      - "main.py" #solo se ejecutara si se hace un push y el archivo main.py es modificado

  pull_request: #Trigger para ejecutar el workflow cuando se crea un pull request
    branches: ["main", "aprendiendo-**"]
    paths:
      - "main.py"

  workflow_dispatch: #Trigger para ejecutar el workflow manualmente
    inputs:
      lenguaje_favorito:
        description: "lenguaje favorito"
        required: true
        default: "python"
        type: choice
        options:
          - python
          - javascript
          - java
      nombre:
        description: "tu nombre"
        required: true
        default: Juan
        type: string

jobs:
  three_triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: definir variable nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: definir variable lenguaje
        run: echo "LENGUAJE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr el script con variables
        run: python main.py
      - name: Finalizando el workflow
        run: echo "workflow finalizado con exito!!"
